### ISSUE TITLE
Cannot find `csv-stringify` imported from wpp-research

### ISSUE THREAD

**Issue by oandregal** [swissspidy/compare-wp-performance#2]
I ran `npm install` and then `./run.sh latest trunk` locally. The process tries to execute, though it fails at running the performance tests. 

If I make sure `wpp-research` has its dependencies installed (`cd wpp-research && npm install`) and then re-execute, it works fine.

See the log:

```log
**Web Vitals (Classic Theme)**

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                            ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'csv-stringify' imported from /home/andre/src/compare-wp-performance/wpp-research/cli/lib/cli/logger.mjs
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:687:9)
    at moduleResolve (internal/modules/esm/resolve.js:728:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'csv-stringify' imported from /home/andre/src/compare-wp-performance/wpp-research/cli/lib/cli/logger.mjs
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:687:9)
    at moduleResolve (internal/modules/esm/resolve.js:728:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
**Server-Timing (Classic Theme)**

✔ Stopped WordPress. (in 14s 559ms)
✔ Stopped WordPress. (in 14s 226ms)
```

**Comment by swissspidy** [comment]
Yay my first bug report! 🙂 

Weird that the dependencies were not installed for you. There's a line for it here:

https://github.com/swissspidy/compare-wp-performance/blob/59d47b237542150bfeb905d0dc2ead11c5b784c8/run.sh#L7

Maybe I need to change from `npm ci` to `npm i` 🤔

**Comment by oandregal** [comment]
It just occurred to me that the OS may have played a role here: I was on a linux machine (Ubuntu OS) when I ran this. :thinking:

**Comment by swissspidy** [comment]
I'm currently working on merging this into the `wpp-research` repo directly, so this issue shouldn't happen anymore.

See https://github.com/GoogleChromeLabs/wpp-research/pull/68
